package midgard.code.thor.api.model.dto;

public record HourlyValuesDto(double cloudBase,
                              String cloudCeiling,
                              int cloudCover,
                              double dewPoint,
                              double evapotranspiration,
                              int freezingRainIntensity,
                              int humidity,
                              int iceAccumulation,
                              int iceAccumulationLwe,
                              int precipitationProbability,
                              double pressureSurfaceLevel,
                              int rainAccumulation,
                              int rainAccumulationLwe,
                              int rainIntensity,
                              int sleetAccumulation,
                              int sleetAccumulationLwe,
                              int sleetIntensity,
                              int snowAccumulation,
                              int snowAccumulationLwe,
                              int snowIntensity,
                              double temperature,
                              double temperatureApparent,
                              int uvHealthConcern,
                              int uvIndex,
                              int visibility,
                              int weatherCode,
                              double windDirection,
                              int windGust,
                              double windSpeed) {
}
